# Getting started with pandas

In [215]:
import pandas as pd

In [216]:
from pandas import Series, DataFrame

In [217]:
import numpy as np

## 5.1 Introduction to pandas Data Structures

### Series

In [218]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [219]:
obj.values

array([ 4,  7, -5,  3])

In [220]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [221]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [222]:
obj2['a']

-5

In [223]:
obj2['d'] = 6

In [224]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [225]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [226]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [227]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [228]:
'b' in obj2

True

In [229]:
'e' in obj2

False

In [230]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [231]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [232]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [233]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [234]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [235]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [236]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [237]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [238]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [239]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [240]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [241]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [242]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [243]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [244]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [245]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [246]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [247]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [248]:
frame.head() # first five rows

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [249]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [250]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [251]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [252]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [253]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [254]:
frame.loc[1]

pop       1.7
state    Ohio
year     2001
Name: 1, dtype: object

In [255]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [256]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [257]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [258]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [259]:
frame2['eastern'] = (frame2.state == 'Ohio')
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [260]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [261]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [262]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [263]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [264]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [265]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [266]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [267]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [268]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

#### Table 5-1. Possible data inputs to DataFrame constructor
![Table%205-1.%20Possible%20data%20inputs%20to%20DataFrame%20constructor](images/Table%205-1.%20Possible%20data%20inputs%20to%20DataFrame%20constructor.png)

### Index Object

In [269]:
obj = pd.Series(range(3), index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [270]:
index[1:]

Index(['b', 'c'], dtype='object')

In [271]:
index[1]

'b'

In [272]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [273]:
obj2 = pd.Series([1.5,-2.5,0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [274]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [275]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [276]:
'Ohio' in frame3.columns

True

In [277]:
2003 in frame3.index 

False

In [278]:
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

#### Table 5-2. Some Index methods and properties

![Table%205-2.%20Some%20Index%20methods%20and%20properties](images/Table%205-2.%20Some%20Index%20methods%20and%20properties.png)

## 5.2 Essential Functionality

### Reindexing

In [279]:
obj = pd.Series([4.5,7.2,-5.3,3.6], index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [280]:
obj.reindex(['a','b','c','d','e'])

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [281]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [282]:
obj3.reindex(range(6), method='ffill') # forward-fill

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [283]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index=['a','c','d'], columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [284]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [285]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [286]:
frame.loc[['a','b','c','d'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

#### Table 5-3. reindex function arguments

![Table%205-3.%20reindex%20function%20arguments](images/Table%205-3.%20reindex%20function%20arguments.png)

### Dropping Entries from an Axis

In [287]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [288]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [289]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering

In [290]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [291]:
obj['b']

1.0

In [292]:
obj[1]

1.0

In [293]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [294]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [295]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [296]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [297]:
obj['a':'c']

a    0.0
b    1.0
c    2.0
dtype: float64

In [298]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [299]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [300]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [301]:
data[['one','three']]

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [302]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [303]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [304]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [305]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Selection with loc and iloc

In [306]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [307]:
data.loc['Colorado', ['two', 'three']]
data.iloc[1,[1,2]]

two      5
three    6
Name: Colorado, dtype: int64

In [308]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [309]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [310]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [311]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [312]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

#### Table 5-4. Indexing options with DataFrame

![Table%205-4.%20Indexing%20options%20with%20DataFrame1](images/Table%205-4.%20Indexing%20options%20with%20DataFrame1.png)
![Table%205-4.%20Indexing%20options%20with%20DataFrame](images/Table%205-4.%20Indexing%20options%20with%20DataFrame2.png)

### Integer Indexes

In [313]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [314]:
ser2 = pd.Series(np.arange(3.), index=['a','b','c'])
ser2[-1]

2.0

In [315]:
ser[:1]

0    0.0
dtype: float64

In [316]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [317]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [318]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [319]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [320]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [321]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [322]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [323]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [324]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1

A
0  1
1  2

In [325]:
df2

B
0  3
1  4

In [326]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [327]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values

In [328]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [329]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [330]:
df2.loc[1, 'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [331]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [332]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [333]:
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [334]:
df1.rdiv(2)

a         b         c         d
0       inf  2.000000  1.000000  0.666667
1  0.500000  0.400000  0.333333  0.285714
2  0.250000  0.222222  0.200000  0.181818

In [335]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Table 5-5. Flexible arithmetic methods

![Table%205-5.%20Flexible%20arithmetic%20methods](images/Table%205-5.%20Flexible%20arithmetic%20methods.png)

#### Operations between DataFrame and Series

In [336]:
arr = np.arange(12.).reshape((3,4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [337]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [338]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [339]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [340]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [341]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [342]:
series2 = pd.Series(range(3), index=['b','e','f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [343]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [344]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [345]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping

In [346]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.332575 -0.574660 -0.500059
Ohio   -0.029170 -0.027581  0.651227
Texas   0.006029 -0.136417  1.179039
Oregon  2.181476 -2.156584  0.429880

In [347]:
np.abs(frame)

b         d         e
Utah    0.332575  0.574660  0.500059
Ohio    0.029170  0.027581  0.651227
Texas   0.006029  0.136417  1.179039
Oregon  2.181476  2.156584  0.429880

In [348]:
f = lambda x: x.max() - x.min() # lambda function object

In [349]:
frame.apply(f, axis='rows')

b    2.210646
d    2.129003
e    1.679098
dtype: float64

In [350]:
frame.apply(f, axis='columns')

Utah      0.907235
Ohio      0.680397
Texas     1.315456
Oregon    4.338061
dtype: float64

In [351]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])
frame.apply(f)

b         d         e
min -0.029170 -2.156584 -0.500059
max  2.181476 -0.027581  1.179039

In [352]:
fmt = lambda x: '%.2f' % x
frame.applymap(fmt)

b      d      e
Utah     0.33  -0.57  -0.50
Ohio    -0.03  -0.03   0.65
Texas    0.01  -0.14   1.18
Oregon   2.18  -2.16   0.43

In [353]:
frame['e'].map(fmt)

Utah      -0.50
Ohio       0.65
Texas      1.18
Oregon     0.43
Name: e, dtype: object

### Sorting and Ranking

In [354]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [355]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [356]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [357]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [358]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [359]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [360]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [361]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [362]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [363]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [364]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [365]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [366]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [367]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [368]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [369]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [370]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [371]:
frame.rank(axis=0)

a    b    c
0  1.5  3.0  2.0
1  3.5  4.0  3.0
2  1.5  1.0  4.0
3  3.5  2.0  1.0

In [372]:
frame.rank(axis='rows')

a    b    c
0  1.5  3.0  2.0
1  3.5  4.0  3.0
2  1.5  1.0  4.0
3  3.5  2.0  1.0

In [373]:
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

In [374]:
frame.rank(axis='columns')

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

#### Table 5-6. Tie-breaking methods with rank

![Table%205-6.%20Tie-breaking%20methods%20with%20rank](images/Table%205-6.%20Tie-breaking%20methods%20with%20rank.png)

### Axis Indexes with Duplicate Labels

In [375]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [376]:
obj.index.is_unique

False

In [377]:
obj['a']

a    0
a    1
dtype: int64

In [378]:
obj['c']

4

In [379]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a  1.353658  0.564498  0.947059
a  0.998802  0.706514  0.568642
b  0.706874  0.935262 -1.011965
b  0.355937  1.299281  0.606183

In [380]:
df.loc['b']

0         1         2
b  0.706874  0.935262 -1.011965
b  0.355937  1.299281  0.606183

## 5.3 Summarizing and Computing Descriptive Statistics

In [381]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [382]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [383]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [384]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

#### Table 5-7. Options for reduction methods

![Table%205-7.%20Options%20for%20reduction%20methods](images/Table%205-7.%20Options%20for%20reduction%20methods.png)

In [385]:
df.idxmax()

one    b
two    d
dtype: object

In [386]:
print(df)
df.cumsum()

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3


one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [387]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [388]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [389]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

#### Table 5-8. Descriptive and summary statistics

![Table%205-8.%20Descriptive%20and%20summary%20statistics](images/Table%205-8.%20Descriptive%20and%20summary%20statistics.png)

### Correlation and Covariance

In [390]:
!pip install pandas_datareader

In [391]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_google(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Close'] for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/pandas_datareader/google/daily.py:40: UnstableAPIWarning: 
The Google Finance API has not been stable since late 2017. Requests seem
to fail at random. Failure is especially common when bulk downloading.

  warnings.warn(UNSTABLE_WARNING, UnstableAPIWarning)


In [392]:
returns = price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2018-01-29 -0.020699 -0.000221 -0.003227 -0.001488
2018-01-30 -0.005894 -0.010114 -0.019065 -0.012564
2018-01-31  0.002755  0.005371  0.000489  0.024477
2018-02-01  0.002090 -0.001915 -0.007941 -0.007894
2018-02-02 -0.043390 -0.047786 -0.020751 -0.026310

In [393]:
returns['MSFT'].corr(returns['IBM'])

0.46499989208606668

In [394]:
returns['MSFT'].cov(returns['IBM'])

7.7584043802311721e-05

In [395]:
returns.MSFT.corr(returns.IBM)

0.46499989208606668

In [396]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.418156  0.354740  0.394028
GOOG  0.418156  1.000000  0.379856  0.481452
IBM   0.354740  0.379856  1.000000  0.465000
MSFT  0.394028  0.481452  0.465000  1.000000

In [397]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000254  0.000101  0.000067  0.000088
GOOG  0.000101  0.000228  0.000068  0.000102
IBM   0.000067  0.000068  0.000141  0.000078
MSFT  0.000088  0.000102  0.000078  0.000197

In [398]:
returns.corrwith(returns.IBM)

AAPL    0.354740
GOOG    0.379856
IBM     1.000000
MSFT    0.465000
dtype: float64

In [399]:
returns.corrwith(volume)

AAPL   -0.067267
GOOG    0.017077
IBM    -0.159260
MSFT   -0.088006
dtype: float64

### Unique Values, Value Counts, and Membership

In [400]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [401]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [402]:
pd.value_counts(obj.values, sort=False)

b    2
d    1
a    3
c    3
dtype: int64

In [403]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [404]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [405]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [406]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

#### Table 5-9. Unique, value counts, and set membership methods

![Table%205-9.%20Unique,%20value%20counts,%20and%20set%20membership%20methods](images/Table%205-9.%20Unique,%20value%20counts,%20and%20set%20membership%20methods.png)

In [407]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4], 'Qu2': [2, 3, 1, 2, 3], 'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [408]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

#### Appendix: Command Testing

In [409]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python

In [410]:
!lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial


In [411]:
%ll

total 0
-rw-r--r-- 1 nbuser  63821 Jan 26 11:36 Python4DataAnalysisCh2.ipynb
-rw-r--r-- 1 nbuser  71881 Jan 26 11:36 Python4DataAnalysisCh3.ipynb
-rw-r--r-- 1 nbuser 175306 Jan 29 20:26 Python4DataAnalysisCh4.ipynb
-rw-r--r-- 1 nbuser 214490 Feb  5 18:22 Python4DataAnalysisCh5.ipynb
-rw-r--r-- 1 nbuser   1586 Jan 26 11:36 README.md
drwxr-xr-x 2 nbuser      0 Jan 31 22:17 dataset/
drwxr-xr-x 2 nbuser      0 Jan 26 11:36 images/
-rw-r--r-- 1 nbuser     10 Feb  5 18:21 test.txt


In [412]:
!touch test.txt

In [413]:
!echo "Hello" > test.txt

In [414]:
!cat test.txt

Hello


In [415]:
arr = np.arange(100)
!echo arr >> test.txt

In [416]:
!cat test.txt

Hello
arr


In [417]:
%pwd

'/home/nbuser/library'

In [418]:
!pwd

/home/nbuser/library


In [419]:
%cd /

/


In [420]:
!pwd

/


In [421]:
%cd ~

/home/nbuser


In [422]:
%cd library/

/home/nbuser/library


In [423]:
!pwd

/home/nbuser/library


In [424]:
%git st

UsageError: Line magic function `%git` not found.


In [ ]:
!git status

In [ ]:
!git add .